# Generated by Django 4.2.17 on 2024-12-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_apiplan_remove_clientapp_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientapp',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='clientapp',
            name='api_key_expires',
        ),
        migrations.AddField(
            model_name='subscription',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='api_key_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
