# Generated by Django 4.2.17 on 2024-12-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_rename_max_requests_per_month_apiplan_max_requests_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiplan',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
