# Generated by Django 4.2.17 on 2024-12-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_apiplan_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiplan',
            name='duration',
            field=models.IntegerField(default=30),
        ),
    ]
