# Generated by Django 4.2.17 on 2024-12-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_apiplan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
