# Generated by Django 4.2.17 on 2024-12-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(default='razorpay', max_length=50),
        ),
    ]
