# Generated by Django 4.2.17 on 2024-12-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_payment_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=10),
        ),
    ]
