# Generated by Django 4.2.17 on 2025-01-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_alter_subscription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapp',
            name='settings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
