# Generated by Django 4.2.17 on 2024-12-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_created_at_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
